config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'
get 'password_resets/new'
get 'password_resets/edit'
get '/help', to: 'static_pages#help'
get '/about', to: 'static_pages#about'
get '/contact', to: 'static_pages#contact'
get '/signup', to: 'users#new'
get '/fish', to: 'static_pages#fish'
get '/foot', to: 'static_pages#foot'
get '/drum', to: 'static_pages#drum'
post '/signup', to: 'users#create'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
    get :following, :followers
    end
  end
resources :account_activations, only: [:edit]
resources :password_resets, only: [:new, :create, :edit, :update]
resources :microposts, only: [:create, :destroy] 
resources :relationships, only: [:create, :destroy]

end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?  
     @micropost = current_user.microposts.build  
     @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def fish
  end
  def foot
  end
  def drum
  end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
   This web site was developed by Henry Franzoni using GIT v 2.11.0, Ruby on RAILs v 5.0.1, Javascript, Bootstrap, CSS, HTML5, SQL Lite, My SQL, and Postgres.  This web site
   uses bitbucket and heroku in the development chain.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  <ul>
  <li>You can Email me at <em>henry@excaliburbritish.com</em>  </li>
  <li>If you're a member of Team Gunio, you can contact me on <a href="https://teamgunio.slack.com">Slack</a></li>
  <Li>If you're a member of ResearchGate, you can contact me on <a href="https://www.researchgate.net">ResearchGate</a></Li>
  <li>You can also contact me on <a href="https://www.facebook.com/hfranzoni3">FaceBook </a> or on <a href="https://www.linkedin.com/in/henry-franzoni-5436307/">Linked In</a></li>

  </ul>
</p>

app/views/static_pages/drum.html.erb
<% provide(:title, "Music") %>
<h1>Music</h1>
I've played drums since age 4.  I more or less retired from playing the drums in 2006, but I was needed, so I came back to play some since 2014.  
I'm no longer driven to be the absolute best I can be on the drums, I'm only practicing once a week, just keeping in touch with my friends the drums.
I've recorded 18 CDs and records over the years, and have been signed and dropped from 4 Indi record companies.  I surmise I'm in the latter part
of my music career, I'm putting together a best of compilation, which hopefully will be put out soon.  Meanwhile, here's a smattering of tunes from some of
the super-great bands I've been in. I loved making music with these people.
<p>
  <dl>
    <center>
  <dt><%= link_to "Caveman Shoestore, '14th Century', 2006", "Caveman_Shoestore_14th_Century.mp3", class: "btn btn-lg btn-primary" %> </dt>
  <dt><%= link_to "Caveman Shoestore, 'I Just Might', 1992", "Caveman_Shoestore_I_Just_Might.mp3", class: "btn btn-lg btn-primary" %> </dt>
  <dt><%= link_to "Caveman Shoestore, 'Lost Horizon', 1992", "Caveman_Shoestore_Lost_Horizon.mp3", class: "btn btn-lg btn-primary" %> </dt>
  <dt><%= link_to "Caveman Shoestore, 'Tractor Pulling a Clown', 1992", "Caveman_Shoestore_Tractor_Pulling_a_Clown.mp3", class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "Caveman Shoestore, 'When Rome Burns, Read the Sports Page', 1992", "Caveman_Shoestore_When_Rome_Burns_Read_the_Sports_Page.mp3", class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The 1st Face Ditch, Space Flight Cat, 2001","Space_Flight_Cat_Face_Ditch.mp3", class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The 1st Face Ditch, 'I am Truck, Eh?', 2001","I_Am_Truck_Eh_Face_Ditch.mp3", class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The 1st Face Ditch, 'Spycam', 2001","Spycam_Face_Ditch.mp3", class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The 1st and 2nd Face Ditch, 'Pan the Goat God' 2001", "The_1st_and_2nd_Face_Ditch_Pan_the_Goat_God.mp3",class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "Boodlers, 'Lose Change' 1994", "Boodlers_Loose_Change.mp3",class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The 2nd Face Ditch, 'Measurement' 1982", "FaceDitch_Measurement.mp3",class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The 2nd Face Ditch, 'Old Ubu's Waltz' 1982", "Face_Ditch_Old_Ubus_Waltz.mp3",class: "btn btn-lg btn-primary" %></dt>
  <dt><%= link_to "The Tone Dogs, 'Spanish Eyes Medley', 1989", "Tone_Dogs_Blue_Gallery_Spanish_Eyes_Medley.mp3", class: "btn btn-lg btn-primary" %> </dt>    
  <dt><%= link_to "The Tone Dogs, 'Brave It', 1989", "Tone_Dogs_Brave_It.mp3", class: "btn btn-lg btn-primary" %> </dt>
  </dl>
  </center>
  <center>
  <dl>
  <dt>All these bands had Fred Chalenor on bass and Henry Franzoni on drums, </dt>
  <dt>the rest of the musicians you hear here are:</dt> 
  <dt>Elaine diFalco - vocals and keys: Caveman Shoestore;</dt> 
  <dt>Amy Denio - vocals, guitar, bass, and sax, and Courtney Von Drehle - sax and keys: the Tone Dogs;</dt> 
  <dt>Neil Mintern - keys: Face Ditch #1; </dt>
  <dt>Craig Flory - sax, Myles Boisen - guitar, and Randy Neal - guitar: Face Ditch #2; </dt>
  <dt>Elliot Sharp - guitar and Joe Trump - drums: The Boodlers.</dt>
  </dl>
<a href="http://store.cdbaby.com/cd/faceditch" target="cdbaby" style="display:inline-block;background:url(http://CDBaby.name/f/a/faceditch.jpg) 18px 2px no-repeat, url(https://content.cdbaby.com/img/links/link-artwork-cart-dark-buy-now.png) 0px 0px no-repeat;background-size:175px, 211px;height:233px;width:211px;" title="Face Ditch: FaceDitch" alt="Face Ditch: FaceDitch" ></a>
<a href="http://store.cdbaby.com/cd/cavemanshoe" target="cdbaby" style="display:inline-block;background:url(http://CDBaby.name/c/a/cavemanshoe.jpg) 18px 2px no-repeat, url(https://content.cdbaby.com/img/links/link-artwork-cart-dark-buy-now.png) 0px 0px no-repeat;background-size:175px, 211px;height:233px;width:211px;" title="Caveman Shoestore: Supersale" alt="Caveman Shoestore: Supersale" ></a>
</center>

app/views/static_pages/fish.html.erb
<% provide(:title, "Software Development/Fisheries") %>
<h1>Network Administation, Project Management, Computers, Programming, Fisheries Data, Natural Resources</h1>
<h2>Looking about for some better things to do with my time</h2>
<p>
  <body>For 20 years I've focused on the problem of salmon, steelhead, lamprey, and sturgeon survival in the Columbia River Basin, mostly on behalf of four tribes in the basin, The Confederated Tribes of the 
  Warm Springs Reservation of Oregon (<acronym>CTWSRO</acronym>), the Confederated Tribes of the Umatilla Indian Reservation (<Acronym>CTUIR</acronym>), 
  the Yakama Nation (<acronym>YN</acronym>), and the Nez Perce Tribe (<acronym>NPT</acronym>).
 
  <p>
  For 35 years I've written software in a succession of languages and configured and administered networks.  When I first came up there was not much specialization in the computer field, software, hardware, networks all
  together, first one had to configure the computers and networks, then one had to write and debug the programs.  I once worked on a study and co-authored some peer reviewed science papers, the <a href="http://www.fpc.org/documents/CSS/174-05-FINAL-CSS2005AR2-23.pdf">Comparative Survival Study</a>, 
  and the <a href="http://www.fpc.org/documents/CSS/FINAL%20COMPLETE%2010%20YEAR%20CSS%20REPORT-8-31-07withfrontpage.pdf">Comparative Survival Study Ten Year Retrospective Analyses Report</a>
  which has had some impact on the court ordered spilling of water over the mainstem dams of the Columbia Basin. I am very proud to have been a member of the scientific team that
  authored this study.  My primary role was to create software and manage a network to assist in the statistical bootstrap analysis of the data. </p>
  <p>I assisted US Fish and Wildlife Service to develop a dewatering model for chinook redds in the Hanford Reach.</p>
  <p>Funded by the Bonneville Power Administration, I recently managed a data project to assist the tribes to begin building <a href="https://www.cbfish.org/Project.mvc/Display/2008-507-00"> 
  data repositories </a>for their natural resource montioring data across the Columbia Basin Region.</p>
  <p>Senator Larry Craig of Idaho once referred to myself and my colleagues as <em>"Ecoterrorists"</em>, one of my greatest achievements when doing computers and science.</p>
  <p>I also spent three years as lead QA bringing new Food Stamp and WIC EBT systems successfully on-line for the state of Wyoming</p>
  <P>I also assisted the States of Wyoming, Utah, and Colorado to bring their new Mountain State Consortium health care elegibility system on-line.</P>
  <p><center><%= link_to "Have a job that needs to be done?  Here's my Project Management Resume/CV.", "HJF_Management_Resume_6_1_18.pdf", 

  class: "btn btn-lg btn-primary" %> </center></p>
  <p><center><%= link_to "And here's my more computer/network generalist resume", "HJF_Technical_Resume_6_1_18.pdf". 

  class: "btn btn-lg btn-primary" %> </center></p>
 </body> 
  

app/views/static_pages/foot.html.erb
<% provide(:title, "Seatco") %>
<h1>Seatco</h1>
I was curious about this place we live and who might live here with us, so I looked around.  Eventually I wrote a couple of books about it.

<p><dl><center>
  
<dt>
  <%= link_to "In the Spirit of Seatco (Amazon-Kindle)","https://www.amazon.com/dp/B01HSJ8CXM", class: "btn btn-lg btn-primary" %>
  
</dt>
</center>  
</dl>
  
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p><center>
No Help at this time my friend.
</center>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %> 
<div class="row"> 
<aside class="col-md-4"> 
<section class="user_info"> 
<%= render 'shared/user_info' %> 
</section> 
<section class="stats">
<%#= render 'shared/stats' %>
</section>
<section class="micropost_form"> 
<%#= render 'shared/micropost_form' %> 
</section> 
</aside>
<div class="col-md-8">
   <%#<h3>Micropost Feed</h3> %>
   <%= render 'shared/feed' %>
</div> 
</div>
<% else %> 
<div class="center jumbotron"> 
<h1>Future Home of Salmon Bot</h1>
<h2>Predictive AI</h2><h2> used to benefit the public </h2>
<br>
<div>
<dl>
<dt><%#= link_to "Music... Bands... Records and CDs", drum_path, class: "btn btn-lg btn-primary" %></dt>
<dt><%#= link_to "Seatco, Sasquatch, and Books", foot_path, class: "btn btn-lg btn-primary" %></dt>
</dl>
<br>
<%#= link_to "Sign Up!", signup_path, class: "btn btn-lg btn-primary" %> 
</div>
<%#= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %> 
<% end %>







            